# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='viewCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterName', models.CharField(choices=[('index', 'index'), ('blog', 'blog')], max_length=20)),
                ('views', models.IntegerField()),
            ],
        ),
    ]
