# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-11 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160712_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcounter',
            name='counterName',
            field=models.CharField(choices=[('index', 'index'), ('blog', 'blog'), ('cv', 'cv')], max_length=20),
        ),
    ]
