# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-13 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161011_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcounter',
            name='counterName',
            field=models.CharField(choices=[('index', 'index'), ('blog', 'blog'), ('cv', 'cv'), ('projects', 'projects')], max_length=20),
        ),
    ]
